version: '2'
services:
  host:
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    hostname: "host"
    networks:
      1-host:
        ipv4_address: 10.10.10.1
      2-red:
        ipv4_address: 11.11.11.1
      3-green:
        ipv4_address: 12.12.12.1
      4-blue:
        ipv4_address: 13.13.13.1
    build:
      context: .
      dockerfile: ./host/Dockerfile
    cap_add:
      - ALL
  red:
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    hostname: "red"
    networks:
      2-red:
        ipv4_address: 11.11.11.2
    build:
      context: .
      dockerfile: ./red/Dockerfile
    cap_add:
      - ALL
  green:
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    hostname: "green"
    networks:
      3-green:
        ipv4_address: 12.12.12.2
    build:
      context: .
      dockerfile: ./green/Dockerfile
    cap_add:
      - ALL
  blue:
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    hostname: "blue"
    networks:
      4-blue:
        ipv4_address: 13.13.13.2
    build:
      context: .
      dockerfile: ./blue/Dockerfile
    cap_add:
      - ALL
networks:
  1-host:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.253
    driver_opts:
      com.docker.network.bridge.name: br_host
      icc: "true"
  2-red:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
          gateway: 11.11.11.253
    driver_opts:
      com.docker.network.bridge.name: br_red
      icc: "true"
  3-green:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 12.12.12.0/24
          gateway: 12.12.12.253
    driver_opts:
      com.docker.network.bridge.name: br_green
      icc: "true"
  4-blue:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 13.13.13.0/24
          gateway: 13.13.13.253
    driver_opts:
      com.docker.network.bridge.name: br_blue
      icc: "true"
