version: '3'
services:
  pt:
    privileged: true
    tty: true
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ~/pt-files:/home/ubuntu/pt-files
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
